apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - ./docker-entrypoint.sh
          env:
            - name: DB_URL
              value: mongodb://db/vidly
          image: backend
          name: backend
          ports:
            - containerPort: 3001
          resources: {}
      restartPolicy: Always
status: {}
