apiVersion: v1
kind: Service
metadata:
  name: todo-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
